version: '3.9'
services:
  database:
    image: postgres:17
    restart: always #unless-stopped # change to always when in production
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file: ".env"

  django:
    build: ./evergreen
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - '8080:8080'
    env_file: ".env"
    depends_on:
      - database 