version: '3.9'
services:
  database:
    image: postgres:17
    restart: always #unless-stopped # change to always when in production
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username123 # this is insecure - needs to be changed
      POSTGRES_PASSWORD: password123 # this is insecure - needs to be changed

  django:
    build: ./evergreen
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - '8080:8080'
    environment:
      WAIT_HOSTS: database:5432
    depends_on:
      - database 