version: '3'
services:
  mongo:
    image: mongo:4.2.5
  web:
    build: ./evergreen
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - '8080:8080'
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo 